/*

EDIT:
ACOMODAR LOS ERRORES DE EDIT PARA QUE SE VEA BIEN VISUALMENTE
ACOMODAR QUE CUANDO HAY UNA IMAGEN EN EL IMG, EL INPUT DE IMG AGARRE Y QUITE LA VALIDACION (REVISAR FOTO DE LA GALERIA)

MENU:
ACOMODAR PRECIO

SHOW:
ACOMODAR MENSAJE DE SI ESTA SEGURO DE QUERER BORRAR 

UPLOAD:
Cuando se suba el precio, permita lo decimales, puse 40.50 y se subio 40


ACOMODAR VISTA DE NAV USER: ESTAN MUY PEGADOS EL NOMBRE DEL USER Y EL GMAIL DEL USER

REVISAR EL ACTIONS PARA CREAR NUEVO REGISTRO DE USUARIO:
Se quito el id_payment, hay que acomodarlo en el INSERT

VISTA DE MODAL PARA AGREGAR AL CARRITO

ACOMODAR LAS RESPUESTAS DE SI LA ACTUALIZACION FUE CORRECTA O NO EN EDITAR PRODUCTO.
AGREGAR VENTANA DE SI ESTA SEGURO DE QUERER ELIMINAR CON ESTILO (DESCARGAR EL PACK PARA ESO)

*/