/*

EDIT:
ACOMODAR LOS ERRORES DE EDIT PARA QUE SE VEA BIEN VISUALMENTE
ACOMODAR QUE CUANDO HAY UNA IMAGEN EN EL IMG, EL INPUT DE IMG AGARRE Y QUITE LA VALIDACION (REVISAR FOTO DE LA GALERIA)

MENU:
ACOMODAR PRECIO
QUE CUANDO SE AGREGUE AL CARRITO ALGO, NO SE MANDE AL INICIO DE LA PAGINA SI NO QUE SE QUEDE ESTATICO
ACOMODAR LA CANTIDAD
ADVERTENCIA DE QUE SI EL STATUS DEL PRODUCTO ESTA EN 2 ENTONCES SALGA UN CARTEL QUE DIGA QUE EL PRODUCTO NO ESTA DISPONIBLE Y NO SE AGREGUE
ACOMODAR LA SECCION PARA EL "ELIGE Y DISFRUTA"

SHOW:
ACOMODAR MENSAJE DE SI ESTA SEGURO DE QUERER BORRAR 

UPLOAD:
Cuando se suba el precio, permita lo decimales, puse 40.50 y se subio 40

PAYMENT:
CUANDO SE CONFIRME EL PAGO, TODOS LOS PRODUCTOS PASEN A STATUS 2 PARA REINICIAR EL CARRITO
EN EL CARRITO, QUITAR EL MAS Y MENOS, nada de correcciones en el PAYMENT QUE SE JO


ACOMODAR VISTA DE NAV USER: ESTAN MUY PEGADOS EL NOMBRE DEL USER Y EL GMAIL DEL USER

REVISAR EL ACTIONS PARA CREAR NUEVO REGISTRO DE USUARIO:
Se quito el id_payment, hay que acomodarlo en el INSERT

VISTA DE MODAL PARA AGREGAR AL CARRITO

ACOMODAR LAS RESPUESTAS DE SI LA ACTUALIZACION FUE CORRECTA O NO EN EDITAR PRODUCTO.
AGREGAR VENTANA DE SI ESTA SEGURO DE QUERER ELIMINAR CON ESTILO (DESCARGAR EL PACK PARA ESO)

*/