/*

SING_IN
FORGOT
VERIFICACION DE QUE EXISTA EL CORREO QUE INGRESO (VER VIDEOS DE CODINNEPAL)
Quitar el recuerdame

EDIT:
ACOMODAR LOS ERRORES DE EDIT PARA QUE SE VEA BIEN VISUALMENTE
ACOMODAR QUE CUANDO HAY UNA IMAGEN EN EL IMG, EL INPUT DE IMG AGARRE Y QUITE LA VALIDACION (REVISAR FOTO DE LA GALERIA)

MENU:
ACOMODAR PRECIO
ACOMODAR QUE CUANDO SE AGREGUE UN MISMO PRODUCTO SE CIERRE LA VENTANA  
ACOMODAR QUE CUANDO SE AGRUEGUE UN MISMO PRODUCTO SE MANDEN LOS CAMBIOS DE LA CANTIDAD SI NO LE HA DADO AUN AL "IR AL PAGO "
ACOMODAR LA SECCION PARA EL "ELIGE Y DISFRUTA"
ACOMODAR EL ESTILO DE SI EL PRODUCTO NO ESTA DISPONIBLE

SHOW:
ACOMODAR MENSAJE DE SI ESTA SEGURO DE QUERER BORRAR 

UPLOAD:
Cuando se suba el precio, permita lo decimales, puse 40.50 y se subio 40

PAYMENT:
CUANDO SE CONFIRME EL PAGO, TODOS LOS PRODUCTOS PASEN A STATUS 2 PARA REINICIAR EL CARRITO
EN EL CARRITO, QUITAR EL MAS Y MENOS, nada de correcciones en el PAYMENT QUE SE JO
ACOMODAR LOS DIV DE ERRORES



REVISAR EL ACTIONS PARA CREAR NUEVO REGISTRO DE USUARIO:
Se quito el id_payment, hay que acomodarlo en el INSERT

ACOMODAR LAS RESPUESTAS DE SI LA ACTUALIZACION FUE CORRECTA O NO EN EDITAR PRODUCTO.
AGREGAR VENTANA DE SI ESTA SEGURO DE QUERER ELIMINAR CON ESTILO (DESCARGAR EL PACK PARA ESO)

*/